add_newline = true
command_timeout = 500

[character]
error_symbol = "[â¯](bold red)"
format = "$symbol "
success_symbol = "[â¯](bold green)"

[directory]
format = "ğŸ“‚ [$path]($style) "
truncation_length = 4

[git_branch]
symbol = "ğŸŒ± "

[package]
symbol = "ğŸ "

[time]
disabled = false
format = "ğŸ•™ $time"
